name: AI Dynamic Pricing

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  update-price:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd backend
          echo "=== Starting dependency installation ==="
          echo "Node.js version:"
          node --version
          echo ""
          echo "npm version:"
          npm --version
          echo ""
          echo "Current directory:"
          pwd
          echo ""
          echo "Files in current directory:"
          ls -la
          echo ""
          echo "Installing dependencies..."
          npm ci --verbose
          echo "=== Dependencies installed ==="
          echo "Installed packages:"
          npm list

      - name: Run pricing script
        env:
          # QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }} # Not used by current script, but good to have if Qwen integration is direct
          METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }} # This will be revenueWallet's private key
          SEPOLIA_URL: ${{ secrets.SEPOLIA_URL }} # Your Sepolia RPC URL
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }} # Deployed AINFTVault contract address
        run: |
          cd backend
          echo "=== Starting dynamic pricing script ==="
          echo "Environment variables:"
          echo "- METAMASK_PRIVATE_KEY is set: ${{ !!secrets.METAMASK_PRIVATE_KEY }}"
          echo "- SEPOLIA_URL is set: ${{ !!secrets.SEPOLIA_URL }}"
          echo "- CONTRACT_ADDRESS is set: ${{ !!secrets.CONTRACT_ADDRESS }}"
          echo ""
          echo "Running script..."
          node dynamic_pricing.js
          echo "=== Script completed ==="
